poll/urls.py
from django.conf.urls import url

from poll import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

sample_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^poll/', include('poll.urls', namespace = 'poll')),
    url(r'^admin/', include(admin.site.urls)),
]

poll/models.py
from __future__ import unicode_literals;
import datetime;

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
	
    def __unicode__(self):
        return self.question_text
		
def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
		
class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)	
        
    def __unicode__(self):
        return self.choice_text

poll/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from poll.models import Choice, Question

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
		"""
		Return the last five published questions (not including those set to be
		published in the future).
		"""
		return Question.objects.filter(
			pub_date__lte=timezone.now()
		).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poll/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('poll:results', args=(p.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'question': question})

poll/templates/poll/base_site.html
{% load staticfiles %}
<!--
	<link rel="stylesheet" type="text/css" href="{% static 'poll/style.css' %}" />
-->
    <link rel="stylesheet" type="text/css" href="{% static 'poll/bootstrap.min.css' %}" />	

{% block content %}{% endblock content %}

poll/templates/poll/detail.html
{% extends 'poll/base_site.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="top">
        <div class="col-md-4">
            <div style = "margin-top: 10%" class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ question.question_text }}</h3>
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                </div>
                    <form class ="container" action="{% url 'poll:vote' question.id %}" method="post">
                        {% csrf_token %}
                        {% for choice in question.choice_set.all %}
                            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
                        {% endfor %}
                        
                    <input class="btn btn-primary btn-sm" type="submit"value="Vote"/>
                    </form>
                </div>
            </div>
            </div>
        <div class="col-md-4">
        </div>
    </div>
</div>
{% endblock content %}

poll/templates/poll/index.html
{% extends 'poll/base_site.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="top">
        <div class="col-md-4">
            <div style = "margin-top: 10%"class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Questions</h3>
                </div>
                
                {% if latest_question_list %}
                <div class="panel-body">
                    
                    <ul class="list-group">
                    {% for question in latest_question_list %}
                    
                        <li class="list-group-item">
                            <a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                    {% else %}
                    <p>No polls are available.</p>
                    {% endif %}
                </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        </div>
    </div>
</div>
{% endblock content %}

poll/templates/poll/results.html
{% load staticfiles %}
<!--
	<link rel="stylesheet" type="text/css" href="{% static 'poll/style.css' %}" />
-->
    <link rel="stylesheet" type="text/css" href="{% static 'poll/bootstrap.min.css' %}" />	


<div class="container">
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="top">
        <div class="col-md-4">
            <div style = "margin-top: 10%" class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ question.question_text }}</h3>
                </div>
                
                <div class="panel-body">
                    
                    <ul class="list-group">
                    {% for choice in question.choice_set.all %}
                    
                        <li class="list-group-item">
                            {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
                        </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            <a href="{% url 'poll:detail' question.id %}">Vote again?</a>
        </div>
        </div>
        <div class="col-md-4">
        </div>
    </div>
</div>